//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaBancaria", Namespace="http://tempuri.org/")]
    public partial class CuentaBancaria : object
    {
        
        private int NumeroCuentaField;
        
        private string ClienteField;
        
        private ServiceReference1.Transaccion[] TransaccionesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroCuenta
        {
            get
            {
                return this.NumeroCuentaField;
            }
            set
            {
                this.NumeroCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cliente
        {
            get
            {
                return this.ClienteField;
            }
            set
            {
                this.ClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceReference1.Transaccion[] Transacciones
        {
            get
            {
                return this.TransaccionesField;
            }
            set
            {
                this.TransaccionesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaccion", Namespace="http://tempuri.org/")]
    public partial class Transaccion : object
    {
        
        private string FechaField;
        
        private string DescripcionField;
        
        private decimal MontoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCuentaBancaria", ReplyAction="*")]
        ServiceReference1.CrearCuentaBancariaResponse CrearCuentaBancaria(ServiceReference1.CrearCuentaBancariaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCuentaBancaria", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CrearCuentaBancariaResponse> CrearCuentaBancariaAsync(ServiceReference1.CrearCuentaBancariaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularSaldo", ReplyAction="*")]
        decimal CalcularSaldo(int numeroCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> CalcularSaldoAsync(int numeroCuenta);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EsDeudorResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EsDeudor", ReplyAction="*")]
        ServiceReference1.EsDeudorResponse EsDeudor(ServiceReference1.EsDeudorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EsDeudor", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.EsDeudorResponse> EsDeudorAsync(ServiceReference1.EsDeudorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarTransaccion", ReplyAction="*")]
        ServiceReference1.AgregarTransaccionResponse AgregarTransaccion(ServiceReference1.AgregarTransaccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarTransaccion", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AgregarTransaccionResponse> AgregarTransaccionAsync(ServiceReference1.AgregarTransaccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsultarCuentaResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarCuenta", ReplyAction="*")]
        ServiceReference1.ConsultarCuentaResponse ConsultarCuenta(ServiceReference1.ConsultarCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ConsultarCuentaResponse> ConsultarCuentaAsync(ServiceReference1.ConsultarCuentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearCuentaBancariaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearCuentaBancaria", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.CrearCuentaBancariaRequestBody Body;
        
        public CrearCuentaBancariaRequest()
        {
        }
        
        public CrearCuentaBancariaRequest(ServiceReference1.CrearCuentaBancariaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearCuentaBancariaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numeroCuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cliente;
        
        public CrearCuentaBancariaRequestBody()
        {
        }
        
        public CrearCuentaBancariaRequestBody(int numeroCuenta, string cliente)
        {
            this.numeroCuenta = numeroCuenta;
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearCuentaBancariaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearCuentaBancariaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.CrearCuentaBancariaResponseBody Body;
        
        public CrearCuentaBancariaResponse()
        {
        }
        
        public CrearCuentaBancariaResponse(ServiceReference1.CrearCuentaBancariaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearCuentaBancariaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.CuentaBancaria CrearCuentaBancariaResult;
        
        public CrearCuentaBancariaResponseBody()
        {
        }
        
        public CrearCuentaBancariaResponseBody(ServiceReference1.CuentaBancaria CrearCuentaBancariaResult)
        {
            this.CrearCuentaBancariaResult = CrearCuentaBancariaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsDeudorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EsDeudor", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.EsDeudorRequestBody Body;
        
        public EsDeudorRequest()
        {
        }
        
        public EsDeudorRequest(ServiceReference1.EsDeudorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EsDeudorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numeroCuenta;
        
        public EsDeudorRequestBody()
        {
        }
        
        public EsDeudorRequestBody(int numeroCuenta)
        {
            this.numeroCuenta = numeroCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsDeudorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EsDeudorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.EsDeudorResponseBody Body;
        
        public EsDeudorResponse()
        {
        }
        
        public EsDeudorResponse(ServiceReference1.EsDeudorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EsDeudorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EsDeudorResult;
        
        public EsDeudorResponseBody()
        {
        }
        
        public EsDeudorResponseBody(string EsDeudorResult)
        {
            this.EsDeudorResult = EsDeudorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarTransaccionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarTransaccion", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AgregarTransaccionRequestBody Body;
        
        public AgregarTransaccionRequest()
        {
        }
        
        public AgregarTransaccionRequest(ServiceReference1.AgregarTransaccionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarTransaccionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numeroCuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal monto;
        
        public AgregarTransaccionRequestBody()
        {
        }
        
        public AgregarTransaccionRequestBody(int numeroCuenta, string fecha, string descripcion, decimal monto)
        {
            this.numeroCuenta = numeroCuenta;
            this.fecha = fecha;
            this.descripcion = descripcion;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarTransaccionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarTransaccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AgregarTransaccionResponseBody Body;
        
        public AgregarTransaccionResponse()
        {
        }
        
        public AgregarTransaccionResponse(ServiceReference1.AgregarTransaccionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AgregarTransaccionResponseBody
    {
        
        public AgregarTransaccionResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCuentaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarCuenta", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ConsultarCuentaRequestBody Body;
        
        public ConsultarCuentaRequest()
        {
        }
        
        public ConsultarCuentaRequest(ServiceReference1.ConsultarCuentaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarCuentaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numeroCuenta;
        
        public ConsultarCuentaRequestBody()
        {
        }
        
        public ConsultarCuentaRequestBody(int numeroCuenta)
        {
            this.numeroCuenta = numeroCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCuentaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ConsultarCuentaResponseBody Body;
        
        public ConsultarCuentaResponse()
        {
        }
        
        public ConsultarCuentaResponse(ServiceReference1.ConsultarCuentaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarCuentaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.CuentaBancaria ConsultarCuentaResult;
        
        public ConsultarCuentaResponseBody()
        {
        }
        
        public ConsultarCuentaResponseBody(ServiceReference1.CuentaBancaria ConsultarCuentaResult)
        {
            this.ConsultarCuentaResult = ConsultarCuentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WebService1SoapChannel : ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ServiceReference1.WebService1Soap>, ServiceReference1.WebService1Soap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.CrearCuentaBancariaResponse ServiceReference1.WebService1Soap.CrearCuentaBancaria(ServiceReference1.CrearCuentaBancariaRequest request)
        {
            return base.Channel.CrearCuentaBancaria(request);
        }
        
        public ServiceReference1.CuentaBancaria CrearCuentaBancaria(int numeroCuenta, string cliente)
        {
            ServiceReference1.CrearCuentaBancariaRequest inValue = new ServiceReference1.CrearCuentaBancariaRequest();
            inValue.Body = new ServiceReference1.CrearCuentaBancariaRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            inValue.Body.cliente = cliente;
            ServiceReference1.CrearCuentaBancariaResponse retVal = ((ServiceReference1.WebService1Soap)(this)).CrearCuentaBancaria(inValue);
            return retVal.Body.CrearCuentaBancariaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CrearCuentaBancariaResponse> ServiceReference1.WebService1Soap.CrearCuentaBancariaAsync(ServiceReference1.CrearCuentaBancariaRequest request)
        {
            return base.Channel.CrearCuentaBancariaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CrearCuentaBancariaResponse> CrearCuentaBancariaAsync(int numeroCuenta, string cliente)
        {
            ServiceReference1.CrearCuentaBancariaRequest inValue = new ServiceReference1.CrearCuentaBancariaRequest();
            inValue.Body = new ServiceReference1.CrearCuentaBancariaRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            inValue.Body.cliente = cliente;
            return ((ServiceReference1.WebService1Soap)(this)).CrearCuentaBancariaAsync(inValue);
        }
        
        public decimal CalcularSaldo(int numeroCuenta)
        {
            return base.Channel.CalcularSaldo(numeroCuenta);
        }
        
        public System.Threading.Tasks.Task<decimal> CalcularSaldoAsync(int numeroCuenta)
        {
            return base.Channel.CalcularSaldoAsync(numeroCuenta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.EsDeudorResponse ServiceReference1.WebService1Soap.EsDeudor(ServiceReference1.EsDeudorRequest request)
        {
            return base.Channel.EsDeudor(request);
        }
        
        public string EsDeudor(int numeroCuenta)
        {
            ServiceReference1.EsDeudorRequest inValue = new ServiceReference1.EsDeudorRequest();
            inValue.Body = new ServiceReference1.EsDeudorRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            ServiceReference1.EsDeudorResponse retVal = ((ServiceReference1.WebService1Soap)(this)).EsDeudor(inValue);
            return retVal.Body.EsDeudorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.EsDeudorResponse> ServiceReference1.WebService1Soap.EsDeudorAsync(ServiceReference1.EsDeudorRequest request)
        {
            return base.Channel.EsDeudorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.EsDeudorResponse> EsDeudorAsync(int numeroCuenta)
        {
            ServiceReference1.EsDeudorRequest inValue = new ServiceReference1.EsDeudorRequest();
            inValue.Body = new ServiceReference1.EsDeudorRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            return ((ServiceReference1.WebService1Soap)(this)).EsDeudorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.AgregarTransaccionResponse ServiceReference1.WebService1Soap.AgregarTransaccion(ServiceReference1.AgregarTransaccionRequest request)
        {
            return base.Channel.AgregarTransaccion(request);
        }
        
        public void AgregarTransaccion(int numeroCuenta, string fecha, string descripcion, decimal monto)
        {
            ServiceReference1.AgregarTransaccionRequest inValue = new ServiceReference1.AgregarTransaccionRequest();
            inValue.Body = new ServiceReference1.AgregarTransaccionRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            inValue.Body.fecha = fecha;
            inValue.Body.descripcion = descripcion;
            inValue.Body.monto = monto;
            ServiceReference1.AgregarTransaccionResponse retVal = ((ServiceReference1.WebService1Soap)(this)).AgregarTransaccion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AgregarTransaccionResponse> ServiceReference1.WebService1Soap.AgregarTransaccionAsync(ServiceReference1.AgregarTransaccionRequest request)
        {
            return base.Channel.AgregarTransaccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AgregarTransaccionResponse> AgregarTransaccionAsync(int numeroCuenta, string fecha, string descripcion, decimal monto)
        {
            ServiceReference1.AgregarTransaccionRequest inValue = new ServiceReference1.AgregarTransaccionRequest();
            inValue.Body = new ServiceReference1.AgregarTransaccionRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            inValue.Body.fecha = fecha;
            inValue.Body.descripcion = descripcion;
            inValue.Body.monto = monto;
            return ((ServiceReference1.WebService1Soap)(this)).AgregarTransaccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.ConsultarCuentaResponse ServiceReference1.WebService1Soap.ConsultarCuenta(ServiceReference1.ConsultarCuentaRequest request)
        {
            return base.Channel.ConsultarCuenta(request);
        }
        
        public ServiceReference1.CuentaBancaria ConsultarCuenta(int numeroCuenta)
        {
            ServiceReference1.ConsultarCuentaRequest inValue = new ServiceReference1.ConsultarCuentaRequest();
            inValue.Body = new ServiceReference1.ConsultarCuentaRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            ServiceReference1.ConsultarCuentaResponse retVal = ((ServiceReference1.WebService1Soap)(this)).ConsultarCuenta(inValue);
            return retVal.Body.ConsultarCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ConsultarCuentaResponse> ServiceReference1.WebService1Soap.ConsultarCuentaAsync(ServiceReference1.ConsultarCuentaRequest request)
        {
            return base.Channel.ConsultarCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ConsultarCuentaResponse> ConsultarCuentaAsync(int numeroCuenta)
        {
            ServiceReference1.ConsultarCuentaRequest inValue = new ServiceReference1.ConsultarCuentaRequest();
            inValue.Body = new ServiceReference1.ConsultarCuentaRequestBody();
            inValue.Body.numeroCuenta = numeroCuenta;
            return ((ServiceReference1.WebService1Soap)(this)).ConsultarCuentaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44313/WebService1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44313/WebService1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService1Soap,
            
            WebService1Soap12,
        }
    }
}
